---
title: "First Knit"
author: "Joseph Elizarraraz"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### I attended Highland High School and I did graduate. I graduated in 2023 and I took a leap year before coming to AVC. Math class is easier to me than English class. Writting essays and doing reports are much harder in my opinion than solving equations. I did the best in math class. I liked my other classes but math class was a bit easier for me than every other subject.      
  
## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### I have an apple laptop at home. It is a Macbook Air and I got it in 2019. I would rate myself at a 7 in computer stuff. I am not the best in coding and other complicated things but I do know the basics of working a computer. Where I live, my internet access is good. It isn't the best but it works and doesn't freeze often.   
  
## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### My preferred name is Joseph. My friends sometimes call me Jojo but I prefer Joseph.     
  
## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### In my lifetime, I'd like to achieve a family and a successful career. These aspirations are important to me and they motivate me to work hard. Political Science right now interests me a lot. That class is the first step to helping me learn more about the profession that I want to get into. I would like to achieve a masters degree in the future. That degree would help me a lot and would bring many job opportunities in my direction.

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### I've been to Mexico before and that's the only outside country I have visited before. In the future, I'd like to visit Brazil and Peru. I have never been in the military before. If I were drafted into the military, I think I would choose the Coast Guard since I would be on defense if we went into war.     
  
## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### Honestly, I am taking Statistics because my counselor recommended it in the 15 minutes I had to meet with her. I did not know that Math 116 had that drastic of a difference. I probably will take that class in a semester or two. In this class, I'd like to get an A but I'll be happy with a B. Even maybe a C as long as I get those credits haha.      
  
   
 






  




